// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreConsoleAPP.Context;

#nullable disable

namespace StoreConsoleAPP.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItemOrder", b =>
                {
                    b.Property<int>("ItemsId")
                        .HasColumnType("int");

                    b.Property<long>("OrdersId")
                        .HasColumnType("bigint");

                    b.HasKey("ItemsId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("ItemOrder");
                });

            modelBuilder.Entity("StoreConsoleAPP.Entities.EmployeeCustomerTips", b =>
                {
                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("TipAmount")
                        .HasColumnType("float");

                    b.HasKey("EmployeeID", "CustomerID");

                    b.HasIndex("CustomerID");

                    b.ToTable("EmployeeCustomerTips");
                });

            modelBuilder.Entity("StoreConsoleAPP.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ITemName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("ItemCategory")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("StoreConsoleAPP.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("money");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BillingAddress", "StoreConsoleAPP.Entities.Order.BillingAddress#FullAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte?>("ApNumber")
                                .HasColumnType("tinyint");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)");

                            b1.Property<string>("Country")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("FirstLine")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<byte?>("FloorNumber")
                                .HasColumnType("tinyint");

                            b1.Property<string>("SecondLine")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ShippingAddress", "StoreConsoleAPP.Entities.Order.ShippingAddress#FullAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte?>("ApNumber")
                                .HasColumnType("tinyint");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)");

                            b1.Property<string>("Country")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("FirstLine")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<byte?>("FloorNumber")
                                .HasColumnType("tinyint");

                            b1.Property<string>("SecondLine")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StoreConsoleAPP.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "StoreConsoleAPP.Entities.Person.Address#FullAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte?>("ApNumber")
                                .HasColumnType("tinyint");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)");

                            b1.Property<string>("Country")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("FirstLine")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<byte?>("FloorNumber")
                                .HasColumnType("tinyint");

                            b1.Property<string>("SecondLine")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");
                        });

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StoreConsoleAPP.Entities.Customer", b =>
                {
                    b.HasBaseType("StoreConsoleAPP.Entities.Person");

                    b.Property<DateTime>("LastVisit")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("StoreConsoleAPP.Entities.Employee", b =>
                {
                    b.HasBaseType("StoreConsoleAPP.Entities.Person");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("ItemOrder", b =>
                {
                    b.HasOne("StoreConsoleAPP.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreConsoleAPP.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreConsoleAPP.Entities.EmployeeCustomerTips", b =>
                {
                    b.HasOne("StoreConsoleAPP.Entities.Customer", "Customer")
                        .WithMany("CustomerTips")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreConsoleAPP.Entities.Employee", "Employee")
                        .WithMany("CustomerTips")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("StoreConsoleAPP.Entities.Order", b =>
                {
                    b.HasOne("StoreConsoleAPP.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("StoreConsoleAPP.Entities.Customer", b =>
                {
                    b.Navigation("CustomerTips");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("StoreConsoleAPP.Entities.Employee", b =>
                {
                    b.Navigation("CustomerTips");
                });
#pragma warning restore 612, 618
        }
    }
}
