//using System;
//using System.Collections.Generic;
//using System.Text;

//namespace D05
//{
//    struct Employee
//    {
//        int id;
//        string name;
//        decimal salary ;

      
//        public Employee(int _id, string _name, decimal _salary)
//        {
//            id = _id;
//            name = _name;
//            salary = _salary;
//        }

//        ///Generated By Vs
//        public int ID { get { return id; } internal set { id = value; } }
//        public string Name { get => name; internal set => name = value; }
//        public decimal Salary { get => salary; internal set => salary = value; }

//        public override string ToString()
//        {
//            return $"id:{id} , name:{name} , salary:{salary}";
//        }
//    }
//}
